### ISSUE TITLE
Please remove my code from this repository.

### ISSUE THREAD

**Issue by mikeshardmind** [ellkbae/Geeci-Cogs#1]
The code which was added in [this commit](https://github.com/ellkbae/Geeci-Cogs/commit/34c22c9e5da55d9dfc0b9de3d4e44b9908c4d1fe) should be removed as this does not adhere to the [license](https://github.com/mikeshardmind/SinbadCogs/blob/v3/LICENSE)

**Comment by ellkbae** [comment]
No worries, code doesn't work anyway as it was used to test out how to implement converted cogs for other cogs, not yours specifically. It was a placeholder to see why the bot wouldn't accept the other cogs in this. None of the cogs are being used until I can figure out to do it correctly.

**Comment by mikeshardmind** [comment]
Thank you.
